# Basic Operations

In [2]:
import torch

In [5]:
# Make the 5 * 3 uninitialized Tensor

In [3]:
x = torch.empty(5,3)

In [4]:
x

tensor([[ 0.0000, -0.0000,  0.0000],
        [-0.0000,  0.0000, -0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])

In [6]:
# Make the random tensor
x = torch.rand(5,3)
x

tensor([[0.1899, 0.2828, 0.8346],
        [0.3518, 0.0437, 0.4526],
        [0.4312, 0.7458, 0.3340],
        [0.1125, 0.9077, 0.9784],
        [0.1877, 0.4851, 0.0612]])

In [8]:
# Construct the zero tensor
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
# Construct Tensor Directly from Data
x = torch.tensor([3,4,5])
print(x)

tensor([3, 4, 5])


In [12]:
# Create tensor Based on the existing Tensor
x = x.new_ones(5,3,dtype=torch.double)
print(x)
x  = torch.rand_like(x,dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.9584, 0.4906, 0.7616],
        [0.0063, 0.9798, 0.0327],
        [0.7131, 0.4405, 0.3272],
        [0.9590, 0.3401, 0.2664],
        [0.3244, 0.3187, 0.2594]])


In [14]:
# Notice that to check the size method must be called
# In numpy the .shape attribute was used
print(x.size())

torch.Size([5, 3])


## Operations in pytorch

In [15]:
# Add the two tensors
y = torch.rand(5,3)
print(x + y)

tensor([[1.8584, 0.5491, 1.0195],
        [0.1915, 1.7719, 0.9157],
        [1.0558, 0.8651, 0.7481],
        [1.3177, 0.4121, 0.5297],
        [0.7851, 0.5243, 1.2446]])


In [16]:
# Another method to add
print(torch.add(x,y))

tensor([[1.8584, 0.5491, 1.0195],
        [0.1915, 1.7719, 0.9157],
        [1.0558, 0.8651, 0.7481],
        [1.3177, 0.4121, 0.5297],
        [0.7851, 0.5243, 1.2446]])


In [18]:
# You also can provide the output tensor as the argument in add()
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[1.8584, 0.5491, 1.0195],
        [0.1915, 1.7719, 0.9157],
        [1.0558, 0.8651, 0.7481],
        [1.3177, 0.4121, 0.5297],
        [0.7851, 0.5243, 1.2446]])


In [19]:
# In place addition
y.add_(x)
print(y)

tensor([[1.8584, 0.5491, 1.0195],
        [0.1915, 1.7719, 0.9157],
        [1.0558, 0.8651, 0.7481],
        [1.3177, 0.4121, 0.5297],
        [0.7851, 0.5243, 1.2446]])


In [22]:
# Slicing is also supported as numpy

print(y[2:,])
print(y[2,:])

tensor([[1.0558, 0.8651, 0.7481],
        [1.3177, 0.4121, 0.5297],
        [0.7851, 0.5243, 1.2446]])
tensor([1.0558, 0.8651, 0.7481])


In [24]:
print(y[:,1])
print(y[1])

tensor([0.5491, 1.7719, 0.8651, 0.4121, 0.5243])
tensor([0.1915, 1.7719, 0.9157])


In [29]:
# Resizing the tensors
# Instead of x.reshape we have x.view
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,2) # Here the size is infered from other dimensions
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([8, 2])


In [32]:
# If we have only one element we can use item to extract the
# Values as the item()
x = torch.rand(1)
print(type(x))
print(type(x.item()))

<class 'torch.Tensor'>
<class 'float'>


## Numpy Bridge

In [34]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [35]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [36]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [37]:
# Converting the numpy array to torch tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Automatic Diffrentiation

<b><i>The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.</b></i>

In [39]:
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [40]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [41]:
print(y.grad_fn)

In [42]:
z = y*y*3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [45]:
# Use requires_grad_ whenever changing the tension behaviour
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


### Gradients

In [46]:
out.backward()

In [50]:
# Prints gradient d(out)/dx
# Gradient can only be called for scalar output
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [52]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [53]:
print(x.requires_grad)


True


# Neural Network

In [54]:
import torch.nn as nn
import torch.nn.functional as F

In [55]:
# Whenever Defining the network Inhereit from torch.nn.Module

In [69]:
class Net(nn.Module):
    
    def __init__(self):
        super(Net, self).__init__()
        
        # Convolution layer
        
        self.conv1 = nn.Conv2d(in_channels=1,out_channels=6,kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6,out_channels=16,kernel_size=5)
        
        # NN layer
        
        self.fc1 = nn.Linear(16*5*5,120) # Always calculate this value Currently It's set for 32*32 Image
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84,10)
        
        
    def forward(self,x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2,2))
        
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        print(x.size())
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self,x):
        size = x.size()[1:]
        num_features = 1
        
        for s in size:
            num_features *= s
        return num_features
    
    

In [70]:
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [60]:
# Learnable Parameters
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 5, 5])


In [63]:
params[2].size()

torch.Size([16, 6, 5, 5])

In [72]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

torch.Size([1, 16, 5, 5])
tensor([[ 0.0154,  0.0641, -0.0877, -0.0168,  0.1358,  0.0966,  0.0481,  0.1314,
         -0.0970, -0.1087]], grad_fn=<ThAddmmBackward>)


In [65]:
net.zero_grad()

In [66]:
out.backward(torch.rand(1,10))

In [73]:
output = net(input)
target = torch.randn(10)
target = target.view(1, -1)
criterion = nn.MSELoss()
loss = criterion(output,target)
print(loss)

torch.Size([1, 16, 5, 5])
tensor(1.0485, grad_fn=<MseLossBackward>)


In [77]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU

#### Backprop

In [78]:
net.zero_grad()

print('Conv1 bias before grad')
print(net.conv1.bias.grad)

loss.backward()

print('Conv1 Bias after the grad')
print(net.conv1.bias.grad)

Conv1 bias before grad
None
Conv1 Bias after the grad
tensor([-0.0039,  0.0322,  0.0326,  0.0082, -0.0429,  0.0241])


#### Update Weights

In [82]:
learning_rate = 0.001
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate)

In [83]:
import torch.optim as opt

In [85]:
optimizer = opt.SGD(net.parameters(),lr=0.01)

# Run in tranning loop
optimizer.zero_grad()
output = net(input)
loss = criterion(output,target)
loss.backward()
optimizer.step()

torch.Size([1, 16, 5, 5])
